version: '2'
services:
  test:
    build: .
    command: npm test
    volumes:
      - .:/usr/app/
  web:
    build: .
    command: npm run live-reload
    volumes:
      - .:/usr/app/
    ports:
      - "8080:80"
    environment:
      APP_PORT: 80